resource_group = "rg-demoapp"
deploy_location = "centralus"
environment = "demo"
department = "none"
app_source = "terraform"
storage_account_tier = "Standard"
storage_account_replication_type = "LRS"