name: Azure Static Web Apps CI/CD

pr:
  branches:
    include:
      - master
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - TodoApp.WebApp/Client
      - azure-pipelines-build-deploy-web-frontend.yml

jobs:
- job: build_and_deploy_job
  displayName: Build and Deploy Job
  condition: or(eq(variables['Build.Reason'], 'Manual'),or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'IndividualCI')))
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: Azure-Static-Web-Apps-kind-field-08e5a8a10-variable-group
  steps:
  
  - checkout: self
    submodules: true
  - task: NodeAndNpmTool@1
    inputs:
     versionSpec: 18.x

  - task: Npm@1
    name: Run_Npm_Install
    inputs:
     command: 'install'
     workingDir: 'TodoApp.WebApp/Client'
  
  - task: Bash@3
    inputs:
      script: ng build
      
      

  - task: Npm@0
    name: buildAngularWebPackage
    inputs:  
      command: run buid
      arguments: --configuration=production --baseUrl=$(TD_BASE_URL)
    env:
      baseUrl: $(TD_BASE_URL)
      
  - task: PublishBuildArtifacts@1
